- hosts: homelab
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install base packages
      apt:
        name:
          - docker.io
          - docker-compose
          - fail2ban
          - ufw
          - unattended-upgrades
        state: present

    - name: Enforce SSH key-only auth
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication no'
      notify: restart sshd

    - name: Allow SSH through UFW
      ufw:
        rule: allow
        name: OpenSSH

    - name: Allow k3s API server
      ufw:
        rule: allow
        port: '6443'
        proto: tcp

    - name: Allow k3s Flannel VXLAN overlay
      ufw:
        rule: allow
        port: '8472'
        proto: udp

    - name: Allow k3s kubelet API
      ufw:
        rule: allow
        port: '10250'
        proto: tcp

    - name: Allow all traffic from home LAN subnet
      ufw:
        rule: allow
        src: 192.168.67.0/24

    - name: Enable UFW
      ufw:
        state: enabled

    - name: Ensure Docker is running and enabled
      service:
        name: docker
        state: started
        enabled: true

  handlers:
    - name: restart sshd
      service:
        name: ssh
        state: restarted